apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwdfh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wwdfh
  template:
    metadata:
      labels:
        app: wwdfh
    spec:
      containers:
      - image: okteto.dev/wwdfh:latest
        name: wwdfh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "cb663c59-49cd-4c09-ae34-9453b90c9e5e"
        - name: Vless_Path
          value: "/vl5dr55"
        - name: Vmess_UUID
          value: "cb663c59-49cd-4c09-ae34-9453b90c9e5e"
        - name: Vmess_Path
          value: "/vm6dfg66"
        - name: Share_Path
          value: "/v2link"
